name: Android CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant Gradle Permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Verify APK Exists
        run: ls app/build/outputs/apk/release/*.apk

      - name: Sign APK
        uses: r0adkll/sign-android-release@v2
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_PASSWORD }}

      - name: Generate Changelog
        run: |
          ./scripts/changelog.sh > CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body_path: CHANGELOG.md
          files: |
            app/build/outputs/apk/release/*-signed.apk

      - name: Sync to Gitee
        if: success()
        run: |
          # 使用优化后的 Gitee 同步脚本
